name: kvis_sf
description: KVIS Science Fair Application

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  connectivity: ^0.4.3+7
  rxdart: ^0.22.3
  url_launcher: ^5.1.2
  firebase_auth: ^0.14.0+5
  firebase_crashlytics: ^0.1.0+2
  firebase_messaging: ^5.1.3
  firebase_storage: ^3.0.6
  cloud_firestore: ^0.12.9+5
  flutter_form_builder: ^3.3.4
  flash: ^1.2.0
  image_picker: ^0.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
